file_format: "1"
id: kukuloco
name: Chocofi Kukuloco
type: shield
url: https://github.com/leikoilja/zmk-config-temper/
requires: [pro_micro]
# exposes: [i2c_oled]
features:
  - keys
  - studio
  # - display
siblings:
  - kukuloco_left
  - kukuloco_right